-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 09:54:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rapido_&_seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapido_&_seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapido_&_seguro`;
USE `rapido_&_seguro` ;

-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`tipoEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`tipoEntrega` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;

INSERT INTO tipoEntrega (nome_tipo) VALUES 
('Normal'),
('Urgente');


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`parametrosCalculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`parametrosCalculo` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_parametro`)
)
ENGINE = InnoDB;

INSERT INTO parametrosCalculo (valor_distancia, valor_peso) VALUES 
(7,10);


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`Pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NOT NULL,
  `distancia_km` DECIMAL(10,2) NOT NULL,
  `peso_kg` DECIMAL(10,2) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `tipoEntrega_id_tipo` INT NOT NULL,
  `id_parametro` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedidos_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_tipoEntrega1_idx` (`tipoEntrega_id_tipo` ASC) VISIBLE,
INDEX `fk_Pedidos_parametro1_idx` (`id_parametro` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_tipoEntrega1`
    FOREIGN KEY (`tipoEntrega_id_tipo`)
    REFERENCES `rapido_&_seguro`.`tipoEntrega` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_Pedidos_paramtro1`
    FOREIGN KEY (`id_parametro`)
    REFERENCES `rapido_&_seguro`.`parametroscalculo` (`id_parametro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`statusEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`statusEntrega` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(20) NOT NULL DEFAULT 'calculando',
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;

INSERT INTO statusEntrega (nome_status) VALUES 
('Calculando'),
('Em transito'),
('Entregue'),
('Cancelado');

select * from statusEntrega;

-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`RegistrosCalculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`RegistrosCalculo` (
  `id_calculo` INT NOT NULL AUTO_INCREMENT,
  `Pedidos_id_pedido` INT NOT NULL,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `taxa_extra` DECIMAL(10,2) NOT NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `statusEntrega_id_status` INT NOT NULL,
  PRIMARY KEY (`id_calculo`),
  INDEX `fk_RegistrosCalculo_Pedidos1_idx` (`Pedidos_id_pedido` ASC) VISIBLE,
  INDEX `fk_RegistrosCalculo_statusEntrega1_idx` (`statusEntrega_id_status` ASC) VISIBLE,
  CONSTRAINT `fk_RegistrosCalculo_Pedidos1`
    FOREIGN KEY (`Pedidos_id_pedido`)
    REFERENCES `rapido_&_seguro`.`Pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistrosCalculo_statusEntrega1`
    FOREIGN KEY (`statusEntrega_id_status`)
    REFERENCES `rapido_&_seguro`.`statusEntrega` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from registrosCalculo;

-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`enderecos` (
  `clientes_id_cliente` INT NOT NULL,
  `rua` VARCHAR(150) NOT NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  INDEX `fk_enderecos_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`telefones` (
  `telefone` VARCHAR(14) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  INDEX `fk_telefones_clientes_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;






-- trigger para inserir as informações na tabela registroCalculos  (trg_calculo_entrega_after_insert)
DELIMITER $$

CREATE TRIGGER trg_calculo_entrega_after_insert
AFTER INSERT ON Pedidos
FOR EACH ROW
BEGIN
    DECLARE v_valor_km DECIMAL(10,2);
    DECLARE v_valor_kg DECIMAL(10,2);
    DECLARE v_valor_distancia DECIMAL(10,2);
    DECLARE v_valor_peso DECIMAL(10,2);
    DECLARE v_valor_base DECIMAL(10,2);
    DECLARE v_acrescimo DECIMAL(10,2) DEFAULT 0;
    DECLARE v_desconto DECIMAL(10,2) DEFAULT 0;
    DECLARE v_taxa_extra DECIMAL(10,2) DEFAULT 0;
    DECLARE v_valor_final DECIMAL(10,2);

    DECLARE v_nome_tipo VARCHAR(20);

    -- Buscar parâmetros de preço
    SELECT valor_distancia, valor_peso
    INTO v_valor_km, v_valor_kg
    FROM parametrosCalculo
    WHERE id_parametro = NEW.id_parametro;

    -- Buscar nome do tipo de entrega
    SELECT nome_tipo
    INTO v_nome_tipo
    FROM tipoEntrega
    WHERE id_tipo = NEW.tipoEntrega_id_tipo;

    -- 1) Calcular valor da distância
    SET v_valor_distancia = NEW.distancia_km * v_valor_km;

    -- 2) Calcular valor do peso
    SET v_valor_peso = NEW.peso_kg * v_valor_kg;

    -- 3) Calcular valor base
    SET v_valor_base = v_valor_distancia + v_valor_peso;

    -- 4) Acréscimo se urgente (20%)
    IF v_nome_tipo = 'Urgente' THEN
        SET v_acrescimo = v_valor_base * 0.20;
    END IF;

    -- valor final preliminar
    SET v_valor_final = v_valor_base + v_acrescimo;

    -- 5) Desconto se valor final > 500 (10%)
    IF v_valor_final > 500 THEN
        SET v_desconto = v_valor_final * 0.10;
        SET v_valor_final = v_valor_final - v_desconto;
    END IF;

    -- 6) Taxa extra se peso > 50kg
    IF NEW.peso_kg > 50 THEN
        SET v_taxa_extra = 15.00;
        SET v_valor_final = v_valor_final + v_taxa_extra;
    END IF;

    -- Inserir resultado final na tabela
    INSERT INTO RegistrosCalculo
    (Pedidos_id_pedido, valor_distancia, valor_peso, acrescimo, desconto, taxa_extra, valor_final, statusEntrega_id_status)
    VALUES
    (NEW.id_pedido, v_valor_distancia, v_valor_peso, v_acrescimo, v_desconto, v_taxa_extra, v_valor_final, 9);

END$$

DELIMITER ;

ALTER TABLE registroscalculo
DROP FOREIGN KEY fk_RegistrosCalculo_Pedidos1;

ALTER TABLE registroscalculo
MODIFY COLUMN Pedidos_id_pedido INT NULL;

ALTER TABLE registroscalculo
ADD CONSTRAINT fk_RegistrosCalculo_Pedidos1
FOREIGN KEY (Pedidos_id_pedido)
REFERENCES pedidos(id_pedido)
ON DELETE SET NULL
ON UPDATE CASCADE;


-- trigger para atualizar as informações na tabela registroCalculos apos update em pedidos (trg_atualiza_valor_calculo_after_update)
DELIMITER $$

CREATE TRIGGER trg_atualiza_valor_calculo_after_update
AFTER UPDATE ON pedidos
FOR EACH ROW
BEGIN
    DECLARE v_valor_distancia DECIMAL(10,2);
    DECLARE v_valor_peso DECIMAL(10,2);
    DECLARE v_valor_base DECIMAL(10,2);
    DECLARE v_acrescimo DECIMAL(10,2);
    DECLARE v_desconto DECIMAL(10,2);
    DECLARE v_taxa_extra DECIMAL(10,2);
    DECLARE v_valor_final DECIMAL(10,2);
    DECLARE v_valor_km DECIMAL(10,2);
    DECLARE v_valor_kg DECIMAL(10,2);

    -- Buscar valores de parâmetro
    SELECT valor_distancia, valor_peso
    INTO v_valor_km, v_valor_kg
    FROM parametrosCalculo
    WHERE id_parametro = NEW.id_parametro;

    -- Cálculo base
    SET v_valor_distancia = NEW.distancia_km * v_valor_km;
    SET v_valor_peso = NEW.peso_kg * v_valor_kg;
    SET v_valor_base = v_valor_distancia + v_valor_peso;

    -- Acréscimo (urgente = 20%)
    IF NEW.tipoEntrega_id_tipo = 2 THEN
        SET v_acrescimo = v_valor_base * 0.20;
    ELSE
        SET v_acrescimo = 0;
    END IF;

    -- Valor inicial com acréscimo
    SET v_valor_final = v_valor_base + v_acrescimo;

    -- Desconto se > 500
    IF v_valor_final > 500 THEN
        SET v_desconto = v_valor_final * 0.10;
        SET v_valor_final = v_valor_final - v_desconto;
    ELSE
        SET v_desconto = 0;
    END IF;

    -- Taxa extra peso > 50 kg
    IF NEW.peso_kg > 50 THEN
        SET v_taxa_extra = 15.00;
        SET v_valor_final = v_valor_final + v_taxa_extra;
    ELSE
        SET v_taxa_extra = 0;
    END IF;

    -- Atualizar a tabela registrosCalculo
    UPDATE registrosCalculo
    SET valor_distancia = v_valor_distancia,
        valor_peso = v_valor_peso,
        acrescimo = v_acrescimo,
        desconto = v_desconto,
        taxa_extra = v_taxa_extra,
        valor_final = v_valor_final,
        statusEntrega_id_status = 9 
    WHERE Pedidos_id_pedido = NEW.id_pedido;

END $$

DELIMITER ;
