-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 09:54:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema rapido_&_seguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapido_&_seguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapido_&_seguro` DEFAULT CHARACTER SET utf8 ;
USE `rapido_&_seguro` ;

-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`tipoEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`tipoEntrega` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`Pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NOT NULL,
  `distancia_km` DECIMAL(10,2) NOT NULL,
  `peso_kg` DECIMAL(10,2) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `tipoEntrega_id_tipo` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedidos_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  INDEX `fk_Pedidos_tipoEntrega1_idx` (`tipoEntrega_id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_tipoEntrega1`
    FOREIGN KEY (`tipoEntrega_id_tipo`)
    REFERENCES `rapido_&_seguro`.`tipoEntrega` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`statusEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`statusEntrega` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(20) NOT NULL DEFAULT 'calculando',
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`RegistrosCalculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`RegistrosCalculo` (
  `id_calculo` INT NOT NULL AUTO_INCREMENT,
  `Pedidos_id_pedido` INT NOT NULL,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `taxa_extra` DECIMAL(10,2) NOT NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `statusEntrega_id_status` INT NOT NULL,
  PRIMARY KEY (`id_calculo`),
  INDEX `fk_RegistrosCalculo_Pedidos1_idx` (`Pedidos_id_pedido` ASC) VISIBLE,
  INDEX `fk_RegistrosCalculo_statusEntrega1_idx` (`statusEntrega_id_status` ASC) VISIBLE,
  CONSTRAINT `fk_RegistrosCalculo_Pedidos1`
    FOREIGN KEY (`Pedidos_id_pedido`)
    REFERENCES `rapido_&_seguro`.`Pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistrosCalculo_statusEntrega1`
    FOREIGN KEY (`statusEntrega_id_status`)
    REFERENCES `rapido_&_seguro`.`statusEntrega` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`enderecos` (
  `clientes_id_cliente` INT NOT NULL,
  `rua` VARCHAR(150) NOT NULL,
  `bairro` VARCHAR(80) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` CHAR(8) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  INDEX `fk_enderecos_clientes1_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes1`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`telefones` (
  `telefone` VARCHAR(14) NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  INDEX `fk_telefones_clientes_idx` (`clientes_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `rapido_&_seguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapido_&_seguro`.`parametrosCalculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapido_&_seguro`.`parametrosCalculo` (
  `id_parametro` INT NOT NULL AUTO_INCREMENT,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `Pedidos_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_parametro`),
  INDEX `fk_parametrosCalculo_Pedidos1_idx` (`Pedidos_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_parametrosCalculo_Pedidos1`
    FOREIGN KEY (`Pedidos_id_pedido`)
    REFERENCES `rapido_&_seguro`.`Pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
